In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
from google.colab import files
uploaded = files.upload()

df = pd.read_csv('dataset.csv')
df.head()

Saving dataset.csv to dataset (1).csv

,State,Crop,Soil_Type,Fertilizer,N,P,K,Rainfall_mm,Temperature_C,Yield_kg_per_acre,Soil_pH,Year
0,Karnataka,Soybean,Loamy,DAP,96,41,51,123,31.06,1899,6.82,2003
1,Odisha,Cotton,Red Soil,Urea,29,36,112,247,33.97,1002,6.41,2002
2,Punjab,Groundnut,Red Soil,Compost,37,38,177,142,24.21,1465,7.06,2015
3,Gujarat,Wheat,Red Soil,Compost,58,77,129,227,30.85,2273,5.93,2022
4,Andhra Pradesh,Cotton,Clay,Organic,108,61,63,263,37.81,1497,6.24,2017

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              1500 non-null   object
 1   Crop               1500 non-null   object
 2   Soil_Type          1500 non-null   object
 3   Fertilizer         1500 non-null   object
 4   N                  1500 non-null   int64
 5   P                  1500 non-null   int64
 6   K                  1500 non-null   int64
 7   Rainfall_mm        1500 non-null   int64
 8   Temperature_C      1500 non-null   float64
 9   Yield_kg_per_acre  1500 non-null   int64
 10  Soil_pH            1500 non-null   float64
 11  Year               1500 non-null   int64
dtypes: float64(2), int64(6), object(4)
memory usage: 140.8+ KB

,N,P,K,Rainfall_mm,Temperature_C,Yield_kg_per_acre,Soil_pH,Year
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,73.438000,61.282667,102.112667,176.806000,28.148547,7881.892667,6.766347,2012.090000
std,37.756932,33.257422,54.362863,73.776182,5.783160,20073.333665,0.724898,7.393218
min,10.000000,5.000000,10.000000,50.000000,18.020000,502.000000,5.500000,2000.000000
25%,41.000000,33.000000,56.000000,113.000000,23.132500,1202.750000,6.120000,2005.000000
50%,70.000000,61.000000,100.000000,176.000000,28.490000,1673.500000,6.795000,2012.000000
75%,106.000000,91.000000,149.000000,242.000000,33.180000,2571.750000,7.400000,2019.000000
max,139.000000,119.000000,199.000000,299.000000,37.960000,89946.000000,8.000000,2024.000000

In [4]:
df.isnull().sum()

State                0
Crop                 0
Soil_Type            0
Fertilizer           0
N                    0
P                    0
K                    0
Rainfall_mm          0
Temperature_C        0
Yield_kg_per_acre    0
Soil_pH              0
Year                 0
dtype: int64

In [5]:
df = df.dropna()

In [9]:
df = df.drop_duplicates()

In [10]:
scaler = StandardScaler()

numeric_columns = df.select_dtypes(include=np.number).columns

df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

In [11]:
df.head()

,State,Crop,Soil_Type,Fertilizer,N,P,K,Rainfall_mm,Temperature_C,Yield_kg_per_acre,Soil_pH,Year
0,Karnataka,Soybean,Loamy,DAP,0.597758,-0.610072,-0.940526,-0.729557,0.503604,-0.298151,0.074040,-1.229915
1,Odisha,Cotton,Red Soil,Urea,-1.177342,-0.760465,0.181937,0.951763,1.006957,-0.342852,-0.491746,-1.365219
2,Punjab,Groundnut,Red Soil,Compost,-0.965390,-0.700308,1.378005,-0.471936,-0.681264,-0.319779,0.405231,0.393735
3,Gujarat,Wheat,Red Soil,Compost,-0.409015,0.472754,0.494755,0.680582,0.467280,-0.279513,-1.154129,1.340865
4,Andhra Pradesh,Cotton,Clay,Organic,0.915687,-0.008502,-0.719714,1.168707,1.671175,-0.318184,-0.726340,0.664344

In [12]:
df.to_csv('cleaned_dataset.csv', index=False)