In [8]:
import pandas as pd
import numpy as np

print("Libraries Imported Successful ✅")

Libraries Imported Successful ✅

In [9]:
df = pd.read_csv("../data/dataset.csv")
print("Dataset Loaded Successfully ✅")
df.shape

Dataset Loaded Successfully ✅

(1500, 12)

In [2]:
df.head()

,State,Crop,Soil_Type,Fertilizer,N,P,K,Rainfall_mm,Temperature_C,Yield_kg_per_acre,Soil_pH,Year
0,Karnataka,Soybean,Loamy,DAP,96,41,51,123,31.06,1899,6.82,2003
1,Odisha,Cotton,Red Soil,Urea,29,36,112,247,33.97,1002,6.41,2002
2,Punjab,Groundnut,Red Soil,Compost,37,38,177,142,24.21,1465,7.06,2015
3,Gujarat,Wheat,Red Soil,Compost,58,77,129,227,30.85,2273,5.93,2022
4,Andhra Pradesh,Cotton,Clay,Organic,108,61,63,263,37.81,1497,6.24,2017

In [19]:
print("Dataset Info:")
df.info()

Dataset Info:
<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              1500 non-null   str
 1   Crop               1500 non-null   str
 2   Soil_Type          1500 non-null   str
 3   Fertilizer         1500 non-null   str
 4   N                  1500 non-null   int64
 5   P                  1500 non-null   int64
 6   K                  1500 non-null   int64
 7   Rainfall_mm        1500 non-null   int64
 8   Temperature_C      1500 non-null   float64
 9   Yield_kg_per_acre  1500 non-null   int64
 10  Soil_pH            1500 non-null   float64
 11  Year               1500 non-null   int64
dtypes: float64(2), int64(6), str(4)
memory usage: 140.8 KB

In [20]:
print("\nStatistical Summary:")
df.describe()

Statistical Summary:

,N,P,K,Rainfall_mm,Temperature_C,Yield_kg_per_acre,Soil_pH,Year
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,73.438000,61.282667,102.112667,176.806000,28.148547,7881.892667,6.766347,2012.090000
std,37.756932,33.257422,54.362863,73.776182,5.783160,20073.333665,0.724898,7.393218
min,10.000000,5.000000,10.000000,50.000000,18.020000,502.000000,5.500000,2000.000000
25%,41.000000,33.000000,56.000000,113.000000,23.132500,1202.750000,6.120000,2005.000000
50%,70.000000,61.000000,100.000000,176.000000,28.490000,1673.500000,6.795000,2012.000000
75%,106.000000,91.000000,149.000000,242.000000,33.180000,2571.750000,7.400000,2019.000000
max,139.000000,119.000000,199.000000,299.000000,37.960000,89946.000000,8.000000,2024.000000

In [10]:

df.isnull().sum()

State                0
Crop                 0
Soil_Type            0
Fertilizer           0
N                    0
P                    0
K                    0
Rainfall_mm          0
Temperature_C        0
Yield_kg_per_acre    0
Soil_pH              0
Year                 0
dtype: int64

In [11]:

df = df.drop_duplicates()

In [25]:
df_encoded = pd.get_dummies(df, drop_first=True)

print("Encoding Completed ✅")
df_encoded.head()

Encoding Completed ✅

,N,P,K,Rainfall_mm,Temperature_C,Yield_kg_per_acre,Soil_pH,Year,State_Bihar,State_Gujarat,...,Crop_Wheat,Soil_Type_Clay,Soil_Type_Loamy,Soil_Type_Red Soil,Soil_Type_Sandy,Fertilizer_DAP,Fertilizer_NPK,Fertilizer_Organic,Fertilizer_Potash,Fertilizer_Urea
0,96,41,51,123,31.06,1899,6.82,2003,False,False,...,False,False,True,False,False,True,False,False,False,False
1,29,36,112,247,33.97,1002,6.41,2002,False,False,...,False,False,False,True,False,False,False,False,False,True
2,37,38,177,142,24.21,1465,7.06,2015,False,False,...,False,False,False,True,False,False,False,False,False,False
3,58,77,129,227,30.85,2273,5.93,2022,False,True,...,True,False,False,True,False,False,False,False,False,False
4,108,61,63,263,37.81,1497,6.24,2017,False,False,...,False,True,False,False,False,False,False,True,False,False

In [27]:
from sklearn.preprocessing import StandardScaler

X = df_encoded.drop("Yield_kg_per_acre", axis=1)
y = df_encoded["Yield_kg_per_acre"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled_df = pd.DataFrame(X_scaled, columns=X.columns)

final_df = pd.concat([X_scaled_df, y.reset_index(drop=True)], axis=1)

final_df.to_csv("cleaned_dataset.csv", index=False)